language: ruby
rvm:
- 2.2
script:
- bundle exec jekyll build --config _config.yml,_config_gh_pages.yml
after_success:
- echo "Pull request number: ${TRAVIS_PULL_REQUEST}"
- echo "Target branch name: ${TRAVIS_BRANCH}"
- if [ $TRAVIS_PULL_REQUEST = 'false' ] && [ $TRAVIS_BRANCH = 'jekyll' ]; then
  chmod +x ./scripts/deploy;
  source scripts/deploy;
  fi;
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO=github.com/Gitlings/gitlings.github.io.git
  - REPO_TARGET_BRANCH=master
sudo: false
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ee4a6f2bdbf6b08b22a9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
