language: ruby
rvm:
- 2.2
script:
- if [ $TRAVIS_PULL_REQUEST = 'true' ]; then git checkout $TRAVIS_BRANCH; fi
- bundle exec jekyll build --config _config.yml,_config_gh_pages.yml
after_success:
- if [ $TRAVIS_PULL_REQUEST = 'true' ] && [ $TRAVIS_BRANCH = 'jekyll' ]; then
  chmod +x ./scripts/deploy
  source scripts/deploy
  fi;
- echo "Finish"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO=github.com/Gitlings/gitlings
  - REPO_TARGET_BRANCH=master
sudo: false
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ee4a6f2bdbf6b08b22a9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
