# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

exclude: [script, vendor, Gemfile, Gemfile.lock]

# Site settings
title: Gitlings
description: > # this means to ignore newlines until "baseurl:"
  "Gitlings" is a russian and english speaking group of people who learn programming and share knowledge to each other and public.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  gitlings

# Build settings
markdown: kramdown

excerpt_separator: <!--more-->
